services:
  - type: web
    name: real-estate-chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    pythonVersion: "3.12.7"
